from sqlalchemy import Column, Integer, String, DateTime, Numeric
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class RumaSAP(Base): 
    __tablename__ = 'RumaSAP'  

    # Definición de columnas
    Id = Column(Integer, primary_key=True, autoincrement=True)
    RumaNro = Column(String(255), nullable=True)
    Cantidad = Column(Integer, nullable=True)
    UM = Column(String(50), nullable=True)
    Codigo = Column(Integer, nullable=True)
    DescripcionMaterial = Column(String(255), nullable=True)
    CentroUbicacion = Column(String(100), nullable=True)
    AlmacenUbicacion = Column(String(100), nullable=True)
    TipoProduccion = Column(String(50), nullable=True)
    CentroProduccion = Column(String(50), nullable=True)
    CalidadPlanta = Column(String(50), nullable=True)
    CierreVta = Column(String(50), nullable=True)
    Posicion = Column(Integer, nullable=True)
    Material = Column(Integer, nullable=True)
    CantPreAsignado = Column(Integer, nullable=True)
    CantTransito = Column(Integer, nullable=True)
    CantLote = Column(Integer, nullable=True)
    LoteExp = Column(String(50), nullable=True)
    UbicacionAlmacen = Column(String(100), nullable=True)
    FechaContabilizacion = Column(String(50), nullable=True)  # Ajustar a DateTime si el formato cambia
    FechaFabricacion = Column(String(50), nullable=True)  # Ajustar a DateTime si el formato cambia
    Certificadora = Column(String(100), nullable=True)
    FAnalFcoQco = Column(DateTime, nullable=True)
    FAnalMicobiol = Column(DateTime, nullable=True)
    FVAnalFcoQco = Column(DateTime, nullable=True)
    FVAnalMicobiol = Column(DateTime, nullable=True)
    ProteinaPorc = Column(Numeric(18, 2), nullable=True)
    TVNmg100g = Column(Numeric(18, 2), nullable=True)
    Histaminappm = Column(Numeric(18, 2), nullable=True)
    HumedadPorc = Column(Numeric(18, 2), nullable=True)
    GrasasPorc = Column(Numeric(18, 2), nullable=True)
    CenizasPorc = Column(Numeric(18, 2), nullable=True)
    ClorurosPorc = Column(Numeric(18, 2), nullable=True)
    ArenaPorc = Column(Numeric(18, 2), nullable=True)
    AcidezPorc = Column(Numeric(18, 2), nullable=True)
    AOppm = Column(Numeric(18, 2), nullable=True)
    Cadmio = Column(Numeric(18, 2), nullable=True)
    Hierro = Column(Numeric(18, 2), nullable=True)
    Proximal = Column(Numeric(18, 2), nullable=True)
    GranulometriaPorc = Column(Numeric(18, 2), nullable=True)
    DensAparGml = Column(Numeric(18, 2), nullable=True)
    DensCompGml = Column(Numeric(18, 2), nullable=True)
    NroFlujoCm = Column(Numeric(18, 2), nullable=True)
    Salmonella = Column(String(50), nullable=True)
    Shiguella = Column(String(50), nullable=True)
    EnterobactUfcG = Column(String(50), nullable=True)
    Intervalo = Column(Integer, nullable=True)
    Nro = Column(String(50), nullable=True)
    ClaseInsp = Column(Integer, nullable=True)
    TempElevadaC = Column(Numeric(18, 2), nullable=True)
    ColorHarina = Column(String(50), nullable=True)
    PresenciaMatExtrana = Column(String(50), nullable=True)
    CamaroncilloPorc = Column(Numeric(18, 2), nullable=True)
    CamaroncilloCualit = Column(String(100), nullable=True)
    BHTNIR = Column(Numeric(18, 2), nullable=True)
    HierroNIR = Column(Numeric(18, 2), nullable=True)
    feccrea = Column(DateTime, nullable=True)
    IdBatch = Column(String(100), nullable=True)
    Upgrade = Column(String(100), nullable=True)
    CALIDAD = Column(String(100), nullable=True)
    TM = Column(Numeric(18, 2), nullable=True)
    KG = Column(Numeric(18, 2), nullable=True)
    Prod = Column(String(100), nullable=True)
    FFab = Column(String(100), nullable=True)
    FFabUltima = Column(DateTime, nullable=True)
    FFabFinal = Column(DateTime, nullable=True)
    
    def __repr__(self):
        return f"<RumaSAP(Id={self.Id}, RumaNro={self.RumaNro}, Cantidad={self.Cantidad})>"
